configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/create_amplicons.smk"
include: "rules/filter_amplicons.smk"
include: "rules/simulate_reads.smk"

rule all:
    input:
        get_final_output(),